sudo: required
dist: trusty

language: node_js
node_js:
  - '10.16'

before_install:
  - echo "Running Before Install..."
  - npm i -g yarn

install:
  - echo "Running Install..."
  - yarn install
  
script:
  - echo "Running Script..."
  - yarn test:coverage

after_success:
  - echo "Running After Success..."