sudo: required
dist: trusty

language: node_js
node_js:
  - '10.16'

before_install:
  - echo "Running Before Install..."
  - npm i -g yarn

install:
  - echo "Running Install..."
  - yarn install
  
script:
  - echo "Running Script..."
  - yarn test:coverage

after_success:
  - echo "Running After Success..."
  - yarn codecov

jobs:
  include:
    - stage: npm release
      node_js: "10.16"
      script: echo "Deploying to npm ..."
      deploy:
        provider: npm
        email: "quirimmo@gmail.com"
        api_key: $NPM_API_KEY
        gem: travis-build-stages-demo
        on: master
        # on: deploy-npm-release
